force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Legal Advisor Associated</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>New Client</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal_Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Client Associated</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HerokuProcessor.cls
public class HerokuProcessor {
    public HttpResponse makeGetCallout() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://altimetrik-bootcamp.herokuapp.com/LegalAccounts');
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        // If the request is successful, parse the JSON response. 
        if(response.getStatusCode() == 200) {
            List<Object> LegalAccountJSON = (List<Object>)JSON.deserializeUntyped(response.getBody());
            List<Legal_Advisor__c> legaladvisorToUpsert = new List<Legal_Advisor__c>();
            List<Client__c> clientToUpsert = new List<Client__c>();
            
            for(Object LegalAccountJSON : legalAdvisorJSON) {

                String accountStatus = (String)legalAdvisorJSON.get('AccountStatus');
                if(accountStatus != null && accountStatus.equals('Enabled')){
                   String accountName = (String)legalAdvisorJSON.get('AccountName');
                   String accountNumber = (String)legalAdvisorJSON.get('AccountNumber');
                  Date asOfDate = Date.parse((String)legalAdvisorJSON.get('AsOfDate'));


                    Legal_Advisor__c legalAdvisor = new Legal_Advisor__c(accountNumber, accountName, accountStatus, asOfDate);

               upsert legalAdvisor;
                } else if (accountStatus.equals('Disable')) { 
                    String accountNumber = (String)legalAdvisorJSON.get('AccountNumber');
                    List<ucl_LegalAdvisor> legalAdvisor = ucl_LegalAdvisor.getLegalAdvisorByAccountNumber(accountNumber);

                    if(!legalAdvisor.isEmpty()) {
                        String accountName = (String)legalAdvisorJSON.get('AccountName');
                        String accountNumber = (String)legalAdvisorJSON.get('AccountNumber');
                        Date asOfDate = Date.parse((String)legalAdvisorJSON.get('AsOfDate'));

                        Legal_Advisor__c legalAdvisor = new Legal_Advisor__c(accountNumber, accountName, accountStatus, asOfDate);
                        update legalAdvisor;
                    }

                }
            
            }
        }
        return response;
    }
}